services:
  postgres:
    image: postgis/postgis:18-3.6
    container_name: safepath-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - "${POSTGRES_PORT}:5432"

    volumes:
      - safepath_postgres_data:/var/lib/postgresql

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

    networks:
      - safepath-network

  redis:
    image: redis:8.10.2
    container_name: safepath-redis
    restart: unless-stopped

    ports:
      - "${REDIS_PORT}:6379"

    command:
      - redis-server
      - --appendonly
      - "yes"

    volumes:
      - safepath_redis_data:/data

    healthcheck:
      test:
        [
          "CMD",
          "redis-cli",
          "ping"
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s

    networks:
      - safepath-network

volumes:
  safepath_postgres_data:
    name: safepath_postgres_data

  safepath_redis_data:
    name: safepath_redis_data

networks:
  safepath-network:
    name: safepath-network
    driver: bridge